/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ScanEventDescriptor ScanEventDescriptor;
typedef struct ScanEvents ScanEvents;


/* --- enums --- */


/* --- messages --- */

struct  ScanEventDescriptor
{
  ProtobufCMessage base;
  ProtobufCBinaryData addr;
  char *name;
  int32_t rssi;
};
#define SCAN_EVENT_DESCRIPTOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scan_event_descriptor__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, 0 }


struct  ScanEvents
{
  ProtobufCMessage base;
  size_t n_events;
  ScanEventDescriptor **events;
};
#define SCAN_EVENTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scan_events__descriptor) \
    , 0,NULL }


/* ScanEventDescriptor methods */
void   scan_event_descriptor__init
                     (ScanEventDescriptor         *message);
size_t scan_event_descriptor__get_packed_size
                     (const ScanEventDescriptor   *message);
size_t scan_event_descriptor__pack
                     (const ScanEventDescriptor   *message,
                      uint8_t             *out);
size_t scan_event_descriptor__pack_to_buffer
                     (const ScanEventDescriptor   *message,
                      ProtobufCBuffer     *buffer);
ScanEventDescriptor *
       scan_event_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scan_event_descriptor__free_unpacked
                     (ScanEventDescriptor *message,
                      ProtobufCAllocator *allocator);
/* ScanEvents methods */
void   scan_events__init
                     (ScanEvents         *message);
size_t scan_events__get_packed_size
                     (const ScanEvents   *message);
size_t scan_events__pack
                     (const ScanEvents   *message,
                      uint8_t             *out);
size_t scan_events__pack_to_buffer
                     (const ScanEvents   *message,
                      ProtobufCBuffer     *buffer);
ScanEvents *
       scan_events__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scan_events__free_unpacked
                     (ScanEvents *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ScanEventDescriptor_Closure)
                 (const ScanEventDescriptor *message,
                  void *closure_data);
typedef void (*ScanEvents_Closure)
                 (const ScanEvents *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor scan_event_descriptor__descriptor;
extern const ProtobufCMessageDescriptor scan_events__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
