/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   scan_event_descriptor__init
                     (ScanEventDescriptor         *message)
{
  static const ScanEventDescriptor init_value = SCAN_EVENT_DESCRIPTOR__INIT;
  *message = init_value;
}
size_t scan_event_descriptor__get_packed_size
                     (const ScanEventDescriptor *message)
{
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_event_descriptor__pack
                     (const ScanEventDescriptor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_event_descriptor__pack_to_buffer
                     (const ScanEventDescriptor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanEventDescriptor *
       scan_event_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanEventDescriptor *)
     protobuf_c_message_unpack (&scan_event_descriptor__descriptor,
                                allocator, len, data);
}
void   scan_event_descriptor__free_unpacked
                     (ScanEventDescriptor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scan_events__init
                     (ScanEvents         *message)
{
  static const ScanEvents init_value = SCAN_EVENTS__INIT;
  *message = init_value;
}
size_t scan_events__get_packed_size
                     (const ScanEvents *message)
{
  assert(message->base.descriptor == &scan_events__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_events__pack
                     (const ScanEvents *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_events__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_events__pack_to_buffer
                     (const ScanEvents *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_events__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanEvents *
       scan_events__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanEvents *)
     protobuf_c_message_unpack (&scan_events__descriptor,
                                allocator, len, data);
}
void   scan_events__free_unpacked
                     (ScanEvents *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scan_events__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scan_event_descriptor__field_descriptors[3] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ScanEventDescriptor, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ScanEventDescriptor, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScanEventDescriptor, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_event_descriptor__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = name */
  2,   /* field[2] = rssi */
};
static const ProtobufCIntRange scan_event_descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scan_event_descriptor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanEventDescriptor",
  "ScanEventDescriptor",
  "ScanEventDescriptor",
  "",
  sizeof(ScanEventDescriptor),
  3,
  scan_event_descriptor__field_descriptors,
  scan_event_descriptor__field_indices_by_name,
  1,  scan_event_descriptor__number_ranges,
  (ProtobufCMessageInit) scan_event_descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scan_events__field_descriptors[1] =
{
  {
    "events",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScanEvents, n_events),
    offsetof(ScanEvents, events),
    &scan_event_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_events__field_indices_by_name[] = {
  0,   /* field[0] = events */
};
static const ProtobufCIntRange scan_events__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor scan_events__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanEvents",
  "ScanEvents",
  "ScanEvents",
  "",
  sizeof(ScanEvents),
  1,
  scan_events__field_descriptors,
  scan_events__field_indices_by_name,
  1,  scan_events__number_ranges,
  (ProtobufCMessageInit) scan_events__init,
  NULL,NULL,NULL    /* reserved[123] */
};
