/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: schema.proto */

#ifndef PROTOBUF_C_schema_2eproto__INCLUDED
#define PROTOBUF_C_schema_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ScanEventDescriptor ScanEventDescriptor;
typedef struct ScanEventList ScanEventList;


/* --- enums --- */


/* --- messages --- */

/*
 * serial name 'org.brotheroftux.locationservice.domain.model.firmware.ScanEventDescriptor'
 */
struct  ScanEventDescriptor
{
  ProtobufCMessage base;
  ProtobufCBinaryData addr;
  int64_t ts;
  double distance;
};
#define SCAN_EVENT_DESCRIPTOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scan_event_descriptor__descriptor) \
    , {0,NULL}, 0, 0 }


/*
 * serial name 'org.brotheroftux.locationservice.domain.model.firmware.ScanEventList'
 */
struct  ScanEventList
{
  ProtobufCMessage base;
  /*
   * WARNING: a default value decoded when value is missing
   */
  size_t n_events;
  ScanEventDescriptor **events;
  int64_t ts;
  ProtobufCBinaryData addr;
};
#define SCAN_EVENT_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scan_event_list__descriptor) \
    , 0,NULL, 0, {0,NULL} }


/* ScanEventDescriptor methods */
void   scan_event_descriptor__init
                     (ScanEventDescriptor         *message);
size_t scan_event_descriptor__get_packed_size
                     (const ScanEventDescriptor   *message);
size_t scan_event_descriptor__pack
                     (const ScanEventDescriptor   *message,
                      uint8_t             *out);
size_t scan_event_descriptor__pack_to_buffer
                     (const ScanEventDescriptor   *message,
                      ProtobufCBuffer     *buffer);
ScanEventDescriptor *
       scan_event_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scan_event_descriptor__free_unpacked
                     (ScanEventDescriptor *message,
                      ProtobufCAllocator *allocator);
/* ScanEventList methods */
void   scan_event_list__init
                     (ScanEventList         *message);
size_t scan_event_list__get_packed_size
                     (const ScanEventList   *message);
size_t scan_event_list__pack
                     (const ScanEventList   *message,
                      uint8_t             *out);
size_t scan_event_list__pack_to_buffer
                     (const ScanEventList   *message,
                      ProtobufCBuffer     *buffer);
ScanEventList *
       scan_event_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scan_event_list__free_unpacked
                     (ScanEventList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ScanEventDescriptor_Closure)
                 (const ScanEventDescriptor *message,
                  void *closure_data);
typedef void (*ScanEventList_Closure)
                 (const ScanEventList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor scan_event_descriptor__descriptor;
extern const ProtobufCMessageDescriptor scan_event_list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_schema_2eproto__INCLUDED */
