/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: schema.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "schema.pb-c.h"
void   scan_event_descriptor__init
                     (ScanEventDescriptor         *message)
{
  static const ScanEventDescriptor init_value = SCAN_EVENT_DESCRIPTOR__INIT;
  *message = init_value;
}
size_t scan_event_descriptor__get_packed_size
                     (const ScanEventDescriptor *message)
{
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_event_descriptor__pack
                     (const ScanEventDescriptor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_event_descriptor__pack_to_buffer
                     (const ScanEventDescriptor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanEventDescriptor *
       scan_event_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanEventDescriptor *)
     protobuf_c_message_unpack (&scan_event_descriptor__descriptor,
                                allocator, len, data);
}
void   scan_event_descriptor__free_unpacked
                     (ScanEventDescriptor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scan_event_descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scan_event_list__init
                     (ScanEventList         *message)
{
  static const ScanEventList init_value = SCAN_EVENT_LIST__INIT;
  *message = init_value;
}
size_t scan_event_list__get_packed_size
                     (const ScanEventList *message)
{
  assert(message->base.descriptor == &scan_event_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_event_list__pack
                     (const ScanEventList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_event_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_event_list__pack_to_buffer
                     (const ScanEventList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_event_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanEventList *
       scan_event_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanEventList *)
     protobuf_c_message_unpack (&scan_event_list__descriptor,
                                allocator, len, data);
}
void   scan_event_list__free_unpacked
                     (ScanEventList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scan_event_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scan_event_descriptor__field_descriptors[3] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ScanEventDescriptor, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ScanEventDescriptor, ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScanEventDescriptor, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_event_descriptor__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  2,   /* field[2] = distance */
  1,   /* field[1] = ts */
};
static const ProtobufCIntRange scan_event_descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scan_event_descriptor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanEventDescriptor",
  "ScanEventDescriptor",
  "ScanEventDescriptor",
  "",
  sizeof(ScanEventDescriptor),
  3,
  scan_event_descriptor__field_descriptors,
  scan_event_descriptor__field_indices_by_name,
  1,  scan_event_descriptor__number_ranges,
  (ProtobufCMessageInit) scan_event_descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scan_event_list__field_descriptors[3] =
{
  {
    "events",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScanEventList, n_events),
    offsetof(ScanEventList, events),
    &scan_event_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ScanEventList, ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ScanEventList, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_event_list__field_indices_by_name[] = {
  2,   /* field[2] = addr */
  0,   /* field[0] = events */
  1,   /* field[1] = ts */
};
static const ProtobufCIntRange scan_event_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scan_event_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanEventList",
  "ScanEventList",
  "ScanEventList",
  "",
  sizeof(ScanEventList),
  3,
  scan_event_list__field_descriptors,
  scan_event_list__field_indices_by_name,
  1,  scan_event_list__number_ranges,
  (ProtobufCMessageInit) scan_event_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
